apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keypair
  description: cfhighlander keypair component
  labels:
    cfhighlander/component: keypair
  annotations:
    backstage.io/source-location: url:https://github.com/theonestack/hl-component-keypair
    github.com/project-slug: theonestack/hl-component-keypair
    cfhighlander/latest-version: 1.2.1
  tags:
    - cfhighlander
  links:
    - url: https://github.com/theonestack
      title: CfHighlander Github Org
      icon: dashboard
      type: admin-dashboard
spec:
  type: library
  lifecycle: production
  owner: base2-randd
  system: cfhighlander